CREATE NONCLUSTERED INDEX [IX_enabled_show_in_matrix] ON [dbo].[product] 
(
	[enabled] ASC,
	[show_in_matrix] ASC
)
INCLUDE ( [product_id]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO